name: representations
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
dependencies:
  - python=3.11
  - poetry>=1.8
  - pip
  - pytorch::pytorch==2.2.2
  - pytorch::torchvision==0.17.2
  - pytorch::pytorch-cuda==12.1
  - nvidia::cuda-version==12.1

  # env-specific
  - datasets
  - scikit-learn
  - ipykernel
  - numpy<2
  - transformers=4.47
  - matplotlib

  # for LIME
  - scikit-image
  - pydoe2
  # - evaluate
  # - diffusers
  # - accelerate
  # - xformers::xformers
  # - wandb
  # - python-dotenv
  # - openai
  # - pydantic
  # - sentence-transformers
  # - umap-learn
  # - bertopic
  # - nbformat
